repos:
  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v3.1.0"
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.9"
    hooks:
      - id: ruff
        stages: [commit]
      - id: ruff-format
        stages: [commit]
